### ISSUE TITLE
SSC is a deadlink

### ISSUE THREAD

**Issue by polarathene** [Gjacquenot/ssc_build#1]
This readme and other similar projects refer to a `scc` repo that doesn't appear to exist?

I was interested in it from a comment you wrote [here in Aug 2018](https://github.com/travis-ci/travis-ci/issues/6224#issuecomment-413452166) about your `travis.yml` deploy approach.

**Comment by Gjacquenot** [comment]
Hi @polarathene ,


These repos are forks from https://github.com/sirehna which holds all repos you are looking for.

The link you are looking is 

https://github.com/sirehna/ssc/blob/master/.travis.yml


You can also have a look at:

- https://github.com/sirehna/ssc
- https://github.com/sirehna/base-image-debian8-gcc492
- https://github.com/sirehna/base-image-centos75-gcc485
- https://github.com/sirehna/base-image-win64-gcc540-posixthreads
- https://github.com/sirehna/base-image-debian9-gcc820
- https://github.com/sirehna/base-image-win64-gcc540-win32threads

**Comment by polarathene** [comment]
I'm already using a glob pattern in deploy, but my matrix uses both OSX and Linux operating systems, they both upload to different draft releases. 

If the releases are not draft and built on tag, then they end up in the same release, however I want to use drafts and update a single draft release until publishing with a tag.

All good, cheers for the links anyhow :)
